services:
  dwpostgres:
    image: postgres:17rc1-alpine3.19
    container_name: dbt_postgres
    env_file: ./.env
    restart: unless-stopped
    ports:
      - "5447:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - airflow

volumes:
  postgres-volume:

networks:
  airflow:
    name: airflow
    driver: bridge